# Generated by Django 5.0.1 on 2024-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_copyofgift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CopyOfGift',
        ),
    ]
