# Generated by Django 5.0.1 on 2024-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gift_images/'),
        ),
    ]
