# Generated by Django 5.0.1 on 2024-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='types',
            field=models.CharField(choices=[('boardgames', 'Board games'), ('books', 'Books'), ('collections', 'Collections'), ('computergames', 'Computer games'), ('home', 'Home'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
